spring.datasource.url=jdbc:postgresql://localhost:5432/formation_db
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=MaCleUltraSecreteEtLonguePourHS2561234567890
# 🔍 Logs détaillés pour déboguer Spring Security
logging.level.org.springframework.security=DEBUG
logging.level.com.ira.formation=DEBUG

# ✅ CORS debug
logging.level.org.springframework.web.cors=DEBUG

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB